#!/bin/bash
USER=`whoami`
SPARK_IDENT_STRING=$USER
SPARK_NICENESS=0
export SPARK_MASTER_PORT=7077
export SPARK_MASTER_WEBUI_PORT=8081
export SPARK_WORKER_WEBUI_PORT=8082
export SPARK_LOG_DIR=/var/log/spark/$USER
export SPARK_PID_DIR=/var/run/spark/$USER
